# =============================================
# SERVIDOR
# =============================================
server.port=${SERVER_PORT}

# =============================================
# BACKEND URL
# =============================================
backend.url=${BACKEND_URL}

# =============================================
# JWT
# =============================================
jwt.secret=${JWT_SECRET}
jwt.cookie.name=${JWT_COOKIE_NAME}
jwt.cookie.max-age=${JWT_COOKIE_MAX_AGE}

# =============================================
# CORS
# =============================================
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}